//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int AchievementTypeID { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual AchievementType AchievementType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
