//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int UserID { get; set; }
        public string Value { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool RememberMe { get; set; }
    
        public virtual User User { get; set; }
    }
}
